<main>


<div>
  <h1>Tout sur la league</h1>
    <p>Les players, les teams et l'éctu des matchs</p>
</div>

<section>
  <h2>La team à la une</h2>
    <div class="cadre-blanc">

      <div class="hibou">
      </div>
      <div>
        <p>Angry owls</p>
          <p>Les players</p>
            <div class="players-box">
              <div class="home-team-players">
                <img src="" alt="">
                <p>Ladso</p>
              </div>
              <div class="home-team-players">
                <img src="" alt="">
                <p>Redwitch</p>
              </div>
              <div class="home-team-players">
                <img src="" alt="">
                <p>Soltan</p>
              </div>
            </div>
      </div>
    </div>
</section>

<section>

  <h2>Les players à la une</h2>
    <div>
      <div>
        <img src="" alt="" />
          <h3>Dundy</h3>
          <p>Chatty Parrots</p>
      </div>
      <div>
        <img src="" alt="" />
          <h3>wofin</h3>
          <p>Panthers</p>
      </div>
      <div>
        <img src="" alt="" />
          <h3>Stonk</h3>
          <p>Sparrow</p>
      </div>
    </div>
</section>

<section>
  <h2>Le dernier match</h2>
    <div>
      <h4>Vendetta vs owls</h4>
        <p>17/01/2024</p>
        <div>
          <div class="left"></div>
          <div class="right"></div>

        </div>
    </div>

</section>
</main>